### PR TITLE
update to mirage 4.0.0 & mirage-xen 7.0.0

### PR DESCRIPTION
**Pull request by palainp**
With this changes it compiles with mirage 4.0 and runs on qubes 4.1.

### CODE REVIEW

**Comment by xaki23** [comment]
as part of the whole mess around (the lower parts of) https://github.com/QubesOS/qubes-issues/issues/6162 and https://github.com/Solo5/solo5/pull/516 i can confirm this branch works at least as much as any other, if not better. 

tl;dr: LGTM, please merge

File: config.ml [hunk 1]
```diff
@@ -31,12 +30,12 @@ let main =
...
       package ~min:"6.1.0" "dns-client";
       package "pf-qubes";
     ]
-    "Unikernel.Main" (random @-> mclock @-> job)
+    "Unikernel.Main" (random @-> mclock @-> time @-> job)
 
 let () =
-  register "qubes-firewall" [main $ default_random $ default_monotonic_clock]
+  register "qubes-firewall" [main $ default_random $ default_monotonic_clock $ default_time]
     ~argv:no_argv
```
[the remark this answers is not in the document]
Comment (palainp) [reply config.ml]: The command that permits to remove this line is in the `README.md` both for new VM creation:
https://github.com/mirage/qubes-mirage-firewall/blob/ef2419bf6f49c646b0a5eb3346fc7ec9555fa04f/README.md?plain=1#L85
and for VM updates:
https://github.com/mirage/qubes-mirage-firewall/blob/ef2419bf6f49c646b0a5eb3346fc7ec9555fa04f/README.md?plain=1#L99
It's ok to be removed. :+1:

Do you think I should also add the command elsewhere?

[the remark this answers is not in the document]
Comment (palainp) [reply config.ml]: The arguments for the kernel come from the `grub.cfg` file : https://github.com/marmarek/qubes-builder-mirage/blob/master/template_scripts/grub.cfg
Regarding other commands to properly setup the template VM, there is a post-install script included in the `.rpm` file, I still need to find if we can provide specific commands to set kernel to `grub2-pvh`.

**Comment by palainp** [comment]
Thanks @hannesm for the mirage update. I manually pinned `mirage.4.2` until the merge in opam-repository and updated the `memory_pressure.ml` + `config.ml` for using `mirage-xen.8.0.0`. It seems to works correctly with the new quick_stat estimation.
For @xaki23 if you want to try before opam-repository is updated, you may:
```
opam update -yu && \
opam pin functoria.4.2.0 git+https://github.com/mirage/mirage.git#main -y && \
opam pin functoria-runtime.4.2.0 git+https://github.com/mirage/mirage.git#main -y && \
opam pin mirage-runtime.4.2.0 git+https://github.com/mirage/mirage.git#main -y && \
opam pin mirage.4.2.0 git+https://github.com/mirage/mirage.git#main -y
```
before compiling with the last commit.

File: config.ml [hunk 2]
```diff
@@ -6,17 +6,16 @@
...
   in
-  let key = Arg.opt ~stage:`Both Arg.int 5_000 info in
-  create "nat_table_size" key
+  let key = Key.Arg.opt ~stage:`Both Key.Arg.int 5_000 info in
+  Key.create "nat_table_size" key
 
 let main =
   foreign
-    ~keys:[Functoria_key.abstract table_size]
+    ~keys:[Key.v table_size]
```
Comment (tommytran732) [inline config.ml:18]: The changes n config.ml breaks compilation

Comment (palainp) [reply config.ml:18]: Thanks for your feedback!

The compilation error is odd, this change is due to a deprecation in mirage 4 and this PR should compiles with mirage 4.2 (the previous pins are no longer required, I'll edit my post). I'm not able to reproduce your compilation failure :(

Can you please check that you're on mirage 4.2.0 with `mirage --version`?

Comment (tommytran732) [reply config.ml:18]: Hi,

I will try compiling it manually later :)

I was actually trying to get it compiled using Docker. As it stands right now, even the main branch is broken, but I managed to fix it by removing `git reset` for `opam-repository` and changing the base Docker image to using ocaml/opam:fedora. ocurrent image has not been updated for years now and Fedora 32 has gone EOL for a long time. I never managed to get it working with your PR though. 

It would be great if you can update the Dockerfile as well

Comment (palainp) [reply config.ml:18]: With the last commit you should be able to compile with the up-to-date mirage version. This should also fix #139.

Comment (tommytran732) [reply config.ml:18]: The build process fails on the final step with `Error: Library "vchan" not found.`

Comment (Szewcson) [reply config.ml:18]: Also got this error.

Comment (palainp) [reply config.ml:18]: I have that too now, I somehow got the build directory disrupting the docker build process with previous builds. I'll try to fix that quickly :)

Comment (palainp) [reply config.ml:18]: The latest commit should fix the issue, it compiles fine on a fresh cloned repository and in fresh debian-11 and fedora-35 appVMs. If I understand the problem correctly, when we try to build solo5, it fails if we don't do a make depend first.

Perhaps @talex5 wants to check if I'm ok with the aggregation of the last two RUN and CMD into a single one?

Comment (Szewcson) [reply config.ml:18]:
```
Step 2/8 : RUN cd ~/opam-repository && git fetch origin master && git reset --hard 479a47921a489d11833e03cf949bfb612bd65e41 && opam update
 ---> Running in 40de662ca481
fatal: unable to connect to github.com:
github.com[0: 140.82.121.4]: errno=Connection timed out
```

I got the internet connection in that VM, and tried to retry the build few times with the same result.

Comment (palainp) [reply config.ml:18]: The commit idin the reset command seems to be the old one '479a47...', maybe you forgot to checkout the mirage4 branch after cloning the repository?

Comment (Szewcson) [reply config.ml:18]: I checked out to this PR and run ./build-with-docker.sh. Should I check out something more?

Comment (palainp) [reply config.ml:18]: You may try:
```
git clone git@github.com:palainp/qubes-mirage-firewall.git test-palainp && \
cd test-palainp && \
git checkout mirage4 && \
sudo ./build-with-docker.sh
```

Comment (Szewcson) [reply config.ml:18]: Yes, You are right.

Comment (tommytran732) [reply config.ml:18]: It builds fine now and the sha256 matches your new value, but the actual VM just crashes right after it launches

Comment (Szewcson) [reply config.ml:18]: Which mode of VM did you use? I switched to pvh and everything works fine.

Comment (tommytran732) [reply config.ml:18]: PVH

**Comment by palainp** [comment]
As @Szewcson I have a correct running here with:
```
[user@dom0 Desktop]$ sha256sum /var/lib/qubes/vm-kernels/mirage-test/vmlinuz 
588e921b9d78a99f6f49d468a7b68284c50dabeba95698648ea52e99b381723b  /var/lib/qubes/vm-kernels/mirage-test/vmlinuz
```
```
[2022-08-12 08:20:21] Solo5: Xen console: port 0x2, ring @0x00000000FEFFF000
[2022-08-12 08:20:21]             |      ___|
[2022-08-12 08:20:21]   __|  _ \  |  _ \ __ \
[2022-08-12 08:20:21] \__ \ (   | | (   |  ) |
[2022-08-12 08:20:21] ____/\___/ _|\___/____/
[2022-08-12 08:20:21] Solo5: Bindings version v0.7.3
[2022-08-12 08:20:21] Solo5: Memory map: 64 MB addressable:
[2022-08-12 08:20:21] Solo5:   reserved @ (0x0 - 0xfffff)
[2022-08-12 08:20:21] Solo5:       text @ (0x100000 - 0x31bfff)
[2022-08-12 08:20:21] Solo5:     rodata @ (0x31c000 - 0x386fff)
[2022-08-12 08:20:21] Solo5:       data @ (0x387000 - 0x544fff)
[2022-08-12 08:20:21] Solo5:       heap >= 0x545000 < stack < 0x4000000
[2022-08-12 08:20:21] 2022-08-12 06:20:21 -00:00: INF [qubes.rexec] waiting for client...
[2022-08-12 08:20:21] 2022-08-12 06:20:21 -00:00: INF [qubes.gui] waiting for client...
[2022-08-12 08:20:21] 2022-08-12 06:20:21 -00:00: INF [qubes.db] connecting to server...
[2022-08-12 08:20:21] 2022-08-12 06:20:21 -00:00: INF [qubes.db] connected
...
```
@tommytran732 can you copy/paste your vm configuration and the last part of the qubes log to help understanding the crash please?

File: config.ml (hunk 2 above)
Comment (palainp) [reply config.ml:18]: Sorry I juste noticed that my comment before mark as resolved this conversation disapeared.

As the compilation seems to be fine now, I resolved this part of the PR and we can discuss juste below on the running issue.

**Comment by tommytran732** [comment]
> As @Szewcson I have a correct running here with:
> 
> ```
> [user@dom0 Desktop]$ sha256sum /var/lib/qubes/vm-kernels/mirage-test/vmlinuz 
> 588e921b9d78a99f6f49d468a7b68284c50dabeba95698648ea52e99b381723b  /var/lib/qubes/vm-kernels/mirage-test/vmlinuz
> ```
> 
> ```
> [2022-08-12 08:20:21] Solo5: Xen console: port 0x2, ring @0x00000000FEFFF000
> [2022-08-12 08:20:21]             |      ___|
> [2022-08-12 08:20:21]   __|  _ \  |  _ \ __ \
> [2022-08-12 08:20:21] \__ \ (   | | (   |  ) |
> [2022-08-12 08:20:21] ____/\___/ _|\___/____/
> [2022-08-12 08:20:21] Solo5: Bindings version v0.7.3
> [2022-08-12 08:20:21] Solo5: Memory map: 64 MB addressable:
> [2022-08-12 08:20:21] Solo5:   reserved @ (0x0 - 0xfffff)
> [2022-08-12 08:20:21] Solo5:       text @ (0x100000 - 0x31bfff)
> [2022-08-12 08:20:21] Solo5:     rodata @ (0x31c000 - 0x386fff)
> [2022-08-12 08:20:21] Solo5:       data @ (0x387000 - 0x544fff)
> [2022-08-12 08:20:21] Solo5:       heap >= 0x545000 < stack < 0x4000000
> [2022-08-12 08:20:21] 2022-08-12 06:20:21 -00:00: INF [qubes.rexec] waiting for client...
> [2022-08-12 08:20:21] 2022-08-12 06:20:21 -00:00: INF [qubes.gui] waiting for client...
> [2022-08-12 08:20:21] 2022-08-12 06:20:21 -00:00: INF [qubes.db] connecting to server...
> [2022-08-12 08:20:21] 2022-08-12 06:20:21 -00:00: INF [qubes.db] connected
> ...
> ```
> 
> @tommytran732 can you copy/paste your vm configuration and the last part of the qubes log to help understanding the crash please?

Sorry for the late reply, where do you get those logs?

I am using the same VM configuration in the README. It when I build Mirage 3.10, but when I replace the vmlinuz with the 4.2 version it just crashes shortly after it launches.

**Comment by palainp** [comment]
The logs come from `tail -f /var/log/xen/console/guest-mirage-test.log`. With a correct running with mirage 3.10 (post solo5+pvh) I don't see what can be your issue now, so the logs will certainly be useful :)

**Comment by tommytran732** [comment]
I figured out what is wrong. I forgot to set qvm-features mirage-firewall no-default-kernelopts 1 :D
For some reason it will happily run with the 3.10 kernel but it crash with 4.2. Anyhow, this is user error on my part. The PR is good to go I think :P

**Comment by tommytran732** [comment]
@palainp Mirage 4.2.1 just came out a few hours ago. Is there any chance you can update this PR? :D

**Comment by palainp** [comment]
@tommytran732 @Szewcson: The build should be fine with mirage 4.2.1 now. I ran into troubles for the compilation, maybe you will have to correctly clean the repository. The shasum has not been changed because the mirage update only affects the build system.

**Comment by hannesm** [comment]
Thanks for all your hard work! :)

**Comment by palainp** [comment]
Thanks @hannesm! I hope it can also be built fine with orb at robbur. The next step will be to work on #115 :)

**Comment by hannesm** [comment]
Yes, see https://builds.robur.coop/job/qubes-firewall/build/4ead4483-4236-4b87-9498-b86ed931df8b -- indeed I just sent you a mail how to approach #115
